# Generated by Django 4.2.3 on 2023-08-29 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0028_rename_children_category_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0004_alter_orderitem_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=16,
                        max_length=16,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "OrderItem",
                "verbose_name_plural": "OrderItems",
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=16,
                        max_length=16,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("initialLat", models.CharField(max_length=30)),
                ("initialLong", models.CharField(max_length=30)),
                ("destLat", models.CharField(max_length=30)),
                ("destLong", models.CharField(max_length=30)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("In Progress", "In Progress"),
                            ("Paid", "Progress"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.orderitems",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
