# Generated by Django 4.2.3 on 2023-08-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_orderitems_orders_remove_orderitem_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="product",
        ),
        migrations.AddField(
            model_name="orderitems",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.orders",
            ),
            preserve_default=False,
        ),
    ]
