# Generated by Django 4.2.3 on 2023-08-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_remove_orders_product_orderitems_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("In Progress", "In Progress"),
                    ("Paid", "Paid"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
