# Generated by Django 4.2.3 on 2023-08-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_person',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
