# Generated by Django 4.2.3 on 2023-08-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orders_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='initialLat',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='initialLong',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='initialLat',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='initialLong',
            field=models.CharField(default='', max_length=30),
        ),
    ]
