# Generated by Django 4.2.3 on 2023-08-31 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_orders_initiallat_remove_orders_initiallong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='initialLat',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='initialLong',
        ),
    ]
