# Generated by Django 4.2.3 on 2023-09-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_remove_orderitems_initiallat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="refNo",
            field=models.CharField(default="", max_length=30),
        ),
    ]
